ci: update publish workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -3,9 +3,10 @@ on:
   workflow_dispatch:
     inputs:
       dry-run:
-        description: "Dry run? (y/N)"
+        description: "Dry run"
         required: true
-        default: "N"
+        type: boolean
+        default: false
 
 jobs:
   publish:
@@ -24,23 +25,16 @@ jobs:
         run: yarn install --immutable --immutable-cache
 
       - name: New version (dry run)
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y')
+        if: github.ref == 'refs/heads/main' && inputs.dry-run
         run: yarn lerna version --yes --no-push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --no-git-tag-version --loglevel=verbose
-
       - name: Configure Git user
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
       - name: New version
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
           yarn lerna version --yes --push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --create-release=github -m 'chore: release [skip ci]'
         env:
@@ -48,17 +42,15 @@ jobs:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           YARN_ENABLE_IMMUTABLE_INSTALLS: false
 
-      - uses: actions/setup-node@v3
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
-        with:
-          node-version: 18
-          registry-url: "https://registry.npmjs.org"
-
-      - run: yarn workspaces foreach --no-private npm publish --tolerate-republish
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+      - name: Publish to npm
+        run: |
+          if [ -z "$NODE_AUTH_TOKEN" ]; then
+            echo "Missing env variable NODE_AUTH_TOKEN"
+            exit 1
+          fi
+          echo >> ./.yarnrc.yml
+          echo "npmAuthToken: $NODE_AUTH_TOKEN" >> ./.yarnrc.yml
+          yarn workspaces foreach --no-private npm publish --tolerate-republish
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
