fix: use NPM_AUTH_TOKEN with yarn

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -82,4 +82,12 @@ jobs:
       - name: Publish to npm
         if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
+          if [ -z "$NPM_AUTH_TOKEN" ]; then
+            echo "Missing env variable NPM_AUTH_TOKEN"
+            exit 1
+          fi
+          echo >> ./.yarnrc.yml
+          echo "npmAuthToken: $NPM_AUTH_TOKEN" >> ./.yarnrc.yml
           yarn workspaces foreach --all --parallel --no-private npm publish --tolerate-republish
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
